spring:
  application:
    name: spring-ai-alibaba-qwq-chat-client-example
  ai:
    dashscope:
      api-key: "sk-773a5ee4f74f4696ba1286c1671ab123"
      chat:
        options:
          model: qwen-plus
